# Generated by Django 4.0.3 on 2022-04-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='dob',
        ),
    ]
